# Generated by Django 4.2.26 on 2025-11-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_expense_expenses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
