# Generated by Django 4.2.26 on 2025-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_delete_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
