# Generated by Django 4.2.26 on 2025-11-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_contact_number_vendor_phone_vendor_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='status',
        ),
    ]
