# Generated by Django 4.2.27 on 2026-02-24 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0009_invoice_approved_at_invoice_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
