# Generated by Django 4.2.27 on 2026-02-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
    ]
