# Generated by Django 4.2.27 on 2026-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_company_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
