# Generated by Django 4.2.27 on 2026-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_subscription_end_date_company_trial_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
