# Generated by Django 4.2.27 on 2026-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='employee_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='expense_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='invoice_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
