# Generated by Django 4.2.27 on 2026-02-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan_allow_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='extra_employee_slots',
            field=models.IntegerField(default=0),
        ),
    ]
