# Generated by Django 4.2.27 on 2026-02-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_extra_employee_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
